const wordTooltips = {
    "もんだいようしを": "Object",
    "ひらいて": "Predicate (Verb in te-form)",
    "ください": "Auxiliary Verb (Polite Request)",
    "わたしは": "Subject",
    "しけんかんの": "Modifier (Examiner's)",
    "いうとおりに": "Adverbial Phrase (As instructed)",
    "ひらいた": "Predicate (Past Tense Verb)",
    "げんごちしき": "Topic (Language Knowledge)",
    "もじ": "Modifier (Characters)",
    "ごい": "Modifier (Vocabulary)",
    "見なれた": "Modifier (Familiar)",
    "たん語を": "Object",
    "見ながら": "Adverbial Phrase (While looking at)",
    "ちゅうい書きを": "Object",
    "読み": "Predicate (Verb in te-form)",
    "じゅけんばんごうと": "Object (Exam number and)",
    "名前を": "Object (Name)",
    "き入する": "Predicate (Verb)",
    "このお話は": "Topic",
    "わたしが": "Subject",
    "日本語を": "Object",
    "みにつけるために": "Adverbial Phrase (To master)",
    "がんばってきた": "Predicate (Past Tense Verb)",
    "もの語です": "Predicate (Copula)",
    "JLPT": "Topic (Japanese Language Proficiency Test)",
    "N5": "Modifier (Level N5)",
    "ある日": "Adverbial Phrase (One day)",
    "友だちから": "Source (From a friend)",
    "きゅうに": "Adverbial Phrase (Suddenly)",
    "しつもんを": "Object (Question)",
    "なげかけられた": "Predicate (Passive Verb)",
    "わたし": "Subject",
    "べんきょうしている": "Predicate (Present Continuous Verb)",
    "りゆう": "Object (Reason)",
    "えっと": "Filler (Well...)",
    "すこし": "Adverbial Phrase (A little)",
    "かんがえ": "Predicate (Verb in te-form)",
    "こむ": "Auxiliary Verb (To be deeply in thought)",
    "日本の": "Modifier (Japanese)",
    "ぶんかを": "Object (Culture)",
    "もっと": "Adverbial Phrase (More)",
    "しりたくて": "Predicate (Want to know)",
    "さ": "Filler (Well...)",
    "さいきん": "Adverbial Phrase (Recently)",
    "はじめたんだ～": "Predicate (Started)",
    "友だちA": "Subject (Friend A)",
    "むずしいの～": "Predicate (Is it difficult?)",
    "まだ": "Adverbial Phrase (Still)",
    "はじめた": "Predicate (Started)",
    "ばかり": "Adverbial Phrase (Just)",
    "だから": "Conjunction (So)",
    "むずしいか": "Predicate (Is it difficult?)",
    "どうか": "Adverbial Phrase (Whether or not)",
    "なんて": "Filler (Something like)",
    "わかんないかな": "Predicate (Don't know)",
    "ところで": "Conjunction (By the way)",
    "きのう": "Adverbial Phrase (Yesterday)",
    "かれしが～い下りゃく": "Predicate (Boyfriend said...)",
    "どうでもいい": "Modifier (Unimportant)",
    "話を": "Object (Story)",
    "小一時間ほど": "Adverbial Phrase (For about an hour)",
    "聞かされた": "Predicate (Was made to listen)",
    "後": "Conjunction (After)",
    "友だちAが": "Subject (Friend A)",
    "やっば": "Interjection (Oh no!)",
    "カレシが": "Subject (Boyfriend)",
    "よんでるぅ": "Predicate (Is calling!)",
    "といいながら": "Adverbial Phrase (While saying)",
    "どこかへ": "Adverbial Phrase (Somewhere)",
    "行ってしまった": "Predicate (Went away)",
    "はぁ": "Interjection (Sigh)",
    "べんきょうに": "Adverbial Phrase (To studying)",
    "もどろ": "Predicate (Let's return)",
    "入もん書を": "Object (Application form)",
    "てに": "Adverbial Phrase (In hand)",
    "とり": "Predicate (Took)",
    "よみ": "Predicate (Read)",
    "はじめた": "Predicate (Started)",
    "あ": "Interjection (Oh)",
    "シャワーを": "Object (Shower)",
    "あび": "Predicate (Take)",
    "わすれた": "Predicate (Forgot)"
  };

  export default wordTooltips;